CREATE TABLE therapeutic_groups ( 
     id_therapeutic_group SERIAL PRIMARY KEY, 
     name                 VARCHAR(200) NOT NULL 
 ); 
  
 CREATE TABLE family ( 
     id_family            SERIAL PRIMARY KEY, 
     name                 VARCHAR(300) NOT NULL, 
     potential_illness    TEXT, 
     id_therapeutic_group INTEGER NOT NULL REFERENCES therapeutic_groups(id_therapeutic_group) 
 ); 
  
 CREATE TABLE laboratory ( 
     id_laboratory SERIAL PRIMARY KEY, 
     name          VARCHAR(200) NOT NULL 
 ); 
  
 CREATE TABLE pharmaceutical_form ( 
     id_pharmaceutical_form SERIAL PRIMARY KEY, 
     name                   VARCHAR(200) NOT NULL 
 ); 
  
 CREATE TABLE posology ( 
     id_posology SERIAL PRIMARY KEY, 
     name        TEXT NOT NULL 
 ); 
  
 CREATE TABLE product_details ( 
     id_product             SERIAL PRIMARY KEY, 
     commercial_name        VARCHAR(200) NOT NULL, 
     generic_name           VARCHAR(200), 
     id_family              INTEGER REFERENCES family(id_family), 
     action_mechanism       TEXT, 
     id_laboratory          INTEGER REFERENCES laboratory(id_laboratory), 
     concentration          VARCHAR(50), 
     id_pharmaceutical_form INTEGER REFERENCES pharmaceutical_form(id_pharmaceutical_form), 
     id_posology            INTEGER REFERENCES posology(id_posology), 
     notes                  TEXT, 
     is_active              BOOLEAN NOT NULL DEFAULT TRUE 
 ); 


-- therapeutic_groups
INSERT INTO therapeutic_groups (id_therapeutic_group, name) VALUES (1, 'Antibióticos');
INSERT INTO therapeutic_groups (id_therapeutic_group, name) VALUES (2, 'Antialérgicos');
INSERT INTO therapeutic_groups (id_therapeutic_group, name) VALUES (3, 'Anti-inflamatorios');
INSERT INTO therapeutic_groups (id_therapeutic_group, name) VALUES (4, 'Anestésicos');
INSERT INTO therapeutic_groups (id_therapeutic_group, name) VALUES (5, 'Ciclopléjicos');
INSERT INTO therapeutic_groups (id_therapeutic_group, name) VALUES (6, 'Lubricantes');
INSERT INTO therapeutic_groups (id_therapeutic_group, name) VALUES (7, 'Antiglaucomatosos');
 
-- ============================================================
-- family
-- ============================================================
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (1, 'Inhibidores de Pared', 'Infecciones oculares bacterianas externas como conjuntivitis, blefaritis o queratitis', 1);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (2, 'Inhibidores de la Membrana Celular', 'Infecciones oculares bacterianas externas como conjuntivitis, blefaritis o queratitis', 1);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (3, 'Inhibidor de la sintesis proteica Sub unidad 50s', 'Infecciones oculares bacterianas externas como conjuntivitis, blefaritis o queratitis', 1);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (4, 'Inhibidores de la subunidad 30s', 'Infecciones oculares bacterianas externas como conjuntivitis, blefaritis o queratitis', 1);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (5, 'Inhibidores de la síntesis proteíca (EF-G)', 'Infecciones oculares bacterianas externas como conjuntivitis, blefaritis o queratitis', 1);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (6, 'Inhibidores de Metabolitos', 'Infecciones oculares bacterianas externas como conjuntivitis, blefaritis o queratitis', 1);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (7, 'Inhibidores de ácidos nucleicos (quinolonas)', 'Infecciones oculares bacterianas externas como conjuntivitis, blefaritis o queratitis', 1);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (8, 'Estabilizadores de membrana', 'Reacciones alérgicas oculares', 2);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (9, 'Antihistamínicos', 'Reacciones alérgicas oculares', 2);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (10, 'Acción Dual', 'Reacciones alérgicas oculares', 2);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (11, 'AINES', 'Dolor e inflamación ocular', 3);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (12, 'Corticoesteroides', 'Inflamaciones crónicas e inflamaciones severas agudas', 3);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (13, 'Inmunomoduladores', 'Inflamaciones crónicas', 3);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (14, 'Anestésicos locales (tipo Éster)', 'Procedimientos oftálmicos que requieren anestesia superficial', 4);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (15, 'Anticolinérgicos (ciclopléjicos)', 'Refracción bajo cicloplejia, uveítis, midriasis preoperatoria', 5);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (16, 'Derivados de celulosa', 'Ojo seco, su uso varía de acuerdo al tipo de ojo seco', 6);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (17, 'Polímeros polivinílicos', 'Ojo seco, su uso varía de acuerdo al tipo de ojo seco', 6);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (18, 'Derivados polisacáridos', 'Ojo seco, su uso varía de acuerdo al tipo de ojo seco', 6);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (19, 'Inmunomodulador (lubricantes)', 'Ojo seco por inflamación crónica de glándulas lagrimales', 6);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (20, 'Betabloqueantes', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (21, 'Análogos de prostaglandinas', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (22, 'Inhibidores de la anhidrasa carbónica', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (23, 'Agonistas α-adrenérgicos', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (24, 'Combinados (β + prostaglandina)', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (25, 'Combinados (α2 + β)', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (26, 'Combinados (triples)', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
INSERT INTO family (id_family, name, potential_illness, id_therapeutic_group) VALUES (27, 'Combinados (α2 + inhibidor CA)', 'Glaucoma de ángulo abierto, hipertensión ocular', 7);
 
-- ============================================================
-- laboratory
-- ============================================================
INSERT INTO laboratory (id_laboratory, name) VALUES (1, 'Oftalmoquímica S.A');
INSERT INTO laboratory (id_laboratory, name) VALUES (2, 'Tecnoquímicas S.A');
INSERT INTO laboratory (id_laboratory, name) VALUES (3, 'MK-Visión');
INSERT INTO laboratory (id_laboratory, name) VALUES (4, 'SAVAL S.A');
INSERT INTO laboratory (id_laboratory, name) VALUES (5, 'Poen');
INSERT INTO laboratory (id_laboratory, name) VALUES (6, 'Alcon');
INSERT INTO laboratory (id_laboratory, name) VALUES (7, 'Allergan');
INSERT INTO laboratory (id_laboratory, name) VALUES (8, 'Sophia');
INSERT INTO laboratory (id_laboratory, name) VALUES (9, 'Théa');
INSERT INTO laboratory (id_laboratory, name) VALUES (10, 'Vital Visión');
INSERT INTO laboratory (id_laboratory, name) VALUES (11, 'Optha');
INSERT INTO laboratory (id_laboratory, name) VALUES (12, 'SYV Pharma');
INSERT INTO laboratory (id_laboratory, name) VALUES (13, 'La Santé');
INSERT INTO laboratory (id_laboratory, name) VALUES (14, 'Oftalmi');
INSERT INTO laboratory (id_laboratory, name) VALUES (15, 'Abbott / AbbVie');
INSERT INTO laboratory (id_laboratory, name) VALUES (16, 'Novartis');
INSERT INTO laboratory (id_laboratory, name) VALUES (17, 'Vidiline');
INSERT INTO laboratory (id_laboratory, name) VALUES (18, 'Cinfa');
INSERT INTO laboratory (id_laboratory, name) VALUES (19, 'Collins');
INSERT INTO laboratory (id_laboratory, name) VALUES (20, 'Axon Pharma SAS');
INSERT INTO laboratory (id_laboratory, name) VALUES (21, 'Especialidades Oftalmológicas S.A');
INSERT INTO laboratory (id_laboratory, name) VALUES (22, 'Procaps S.A');
INSERT INTO laboratory (id_laboratory, name) VALUES (23, 'Pfizer');
INSERT INTO laboratory (id_laboratory, name) VALUES (24, 'Terravital');
INSERT INTO laboratory (id_laboratory, name) VALUES (25, 'Leo Pharma');
INSERT INTO laboratory (id_laboratory, name) VALUES (26, 'Blaskov');
INSERT INTO laboratory (id_laboratory, name) VALUES (27, 'Megalabs');
INSERT INTO laboratory (id_laboratory, name) VALUES (28, 'Bausch + Lomb');
INSERT INTO laboratory (id_laboratory, name) VALUES (29, 'Tecnofar TQ');
INSERT INTO laboratory (id_laboratory, name) VALUES (30, 'Varios / Genérico');
 
-- pharmaceutical_form
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (1, 'Solución oftálmica');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (2, 'Unguento oftálmico');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (3, 'Gel oftálmico');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (4, 'Emulsión oftálmica');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (5, 'Gotas oftálmicas');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (6, 'Solución oftálmica unidosis');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (7, 'Suspensión oftálmica');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (8, 'Solución y unguento');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (9, 'Solución / Gel oftálmico');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (10, 'Colirio y unguento');
INSERT INTO pharmaceutical_form (id_pharmaceutical_form, name) VALUES (11, 'Solución tópica');
 
-- posology
INSERT INTO posology (id_posology, name) VALUES (1, 'Aplicar 1 gota en cada ojo cada 6 horas por 7 días');
INSERT INTO posology (id_posology, name) VALUES (2, 'Aplicar 1 gota en cada ojo cada 12 horas por 7 días');
INSERT INTO posology (id_posology, name) VALUES (3, 'Aplicar 1 gota en cada ojo 3 veces al día por 15 días');
INSERT INTO posology (id_posology, name) VALUES (4, 'Aplicar 1 gota cada 12 horas por 2-3 meses y suspender');
INSERT INTO posology (id_posology, name) VALUES (5, 'Aplicar 1 gota cada 12 horas por 2 meses y suspender');
INSERT INTO posology (id_posology, name) VALUES (6, '1-2 gotas en el saco conjuntival antes del procedimiento oftálmico; repetir si es necesario (bajo supervisión médica)');
INSERT INTO posology (id_posology, name) VALUES (7, 'Aplicar una gota entre 30-40 minutos antes del examen bajo cicloplejia, puede aplicar una segunda dosis si es necesario 5 minutos después');
INSERT INTO posology (id_posology, name) VALUES (8, 'Aplicar una gota en cada ojo dependiendo del efecto deseado');
INSERT INTO posology (id_posology, name) VALUES (9, 'Aplicar 1 gota en cada ojo 3 veces al día hasta terminar frasco');
INSERT INTO posology (id_posology, name) VALUES (10, '1 gota cada 12 h');
INSERT INTO posology (id_posology, name) VALUES (11, '1 gota al día (noche)');
INSERT INTO posology (id_posology, name) VALUES (12, '1 gota al día');
INSERT INTO posology (id_posology, name) VALUES (13, '1 gota 2 veces/día');
INSERT INTO posology (id_posology, name) VALUES (14, 'Aplicar en fondo de saco cada 8 horas');
INSERT INTO posology (id_posology, name) VALUES (15, 'Dosificar según el caso y bajar la dosificación gradualmente (1 gota 3v/d, luego 2v/d, luego 1v/d y suspender)');
INSERT INTO posology (id_posology, name) VALUES (16, '1 gota en cada ojo cada 12h, tiempo según cada caso');
INSERT INTO posology (id_posology, name) VALUES (17, 'Aplicar 1 gota en cada ojo cada 8 horas (si hay ardor, cada 12 horas)');
INSERT INTO posology (id_posology, name) VALUES (18, 'Pendiente');
 
-- ============================================================
-- product_details
-- ============================================================
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (1, 'Altracine-A', 'Bacitracina', 1, 'Bactericida', 1, '0.0005', 2, 2, 'Viene acompañado de Polimixina B + Dexametasona 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (2, 'Wassetrol', 'Polimixina B', 2, 'Dañan la membrana citoplasmatica de las bacterias, generando poros actuando como detergente. Eficaz en pseudomonas y gram negativas.', 2, NULL, 2, 1, 'Viene acompañado de Neomicina + Dexametasona', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (3, 'Oxyoftal', 'Polimixina B', 2, 'Dañan la membrana citoplasmatica de las bacterias, generando poros actuando como detergente. Eficaz en pseudomonas y gram negativas.', 2, '0.5%', 2, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (4, 'Mixoftal', 'Polimixina B', 2, 'Dañan la membrana citoplasmatica de las bacterias, generando poros actuando como detergente. Eficaz en pseudomonas y gram negativas.', 3, '0.5%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (5, 'Oftabiotico', 'Polimixina B', 2, 'Dañan la membrana citoplasmatica de las bacterias, generando poros actuando como detergente. Eficaz en pseudomonas y gram negativas.', 4, '0.06%', 1, NULL, 'Viene con Gramicidina + Neomicina', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (6, 'Iloticina Plus', 'Eritromicina', 3, 'Se une a la subunidad 50s para evitar la formación de proteínas. De efecto bacteriostático. Efectivo en gram positivas principalmente.', 2, '0.04%', 11, 1, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (7, 'Eritrofarm', 'Eritromicina', 3, 'Se une a la subunidad 50s para evitar la formación de proteínas. De efecto bacteriostático. Efectivo en gram positivas principalmente.', 5, '1% y 0.5%', 8, NULL, '1% unguento unidosis, 0.5% solución', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (8, 'Azydrop', 'Azitromicina', 3, 'Se une a la subunidad 50s para evitar la formación de proteínas. De efecto bacteriostático. Efectivo en gram positivas principalmente.', 20, '1.43%', 6, NULL, 'Viene sin conservantes', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (9, 'Meibos', 'Azitromicina', 3, 'Se une a la subunidad 50s para evitar la formación de proteínas. De efecto bacteriostático. Efectivo en gram positivas principalmente.', 21, '0.015%', 1, NULL, 'Favorece Meibogénesis', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (10, 'Cloranfenicol', 'Cloranfenicol', 3, 'Se une a la subunidad 50s para evitar la formación de proteínas. De efecto bacteriostático. Efectivo en gram positivas principalmente.', 30, '0.5%, 1%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (11, 'Oftagen', 'Gentamicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 4, '0.3%', 8, 1, 'Viene con 0.1% de betametasona', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (12, 'Provisual', 'Gentamicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 5, '0.3%', NULL, NULL, 'Viene con 0.15% de dexametasona y 0.125% de tetrahidrozolina', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (13, 'Provisual Compuesto', 'Gentamicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 5, '0.3%', 7, NULL, 'Viene combinado con dexametasona y tetrahidrozolina 0.125%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (14, 'Oftalbiotico', 'Neomicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 4, '0.3%', 10, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (15, 'Decadron', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 2, '0.35%', 1, NULL, 'Viene con dexametasona fosfato 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (16, 'Tobrex', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 6, '0.3%', 10, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (17, 'Tobradex', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 20, '0.3%', 7, NULL, 'Viene con dexametasona al 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (18, 'Trazidex', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 8, '0.3%', 9, NULL, 'Viene con dexametasona al 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (19, 'Terramicina', 'Oxitetraciclina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando una formación errónea de las proteínas esenciales para la bacteria.', 23, '0.005', 2, NULL, 'Viene acompañado de polimixina B', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (20, 'Fucithalmic', 'Ácido fusídico', 5, 'Inhibe el factor de elongación G (EF-G)', 25, '0.01', 1, 1, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (21, 'Blef-10 con lagrifilm', 'Sulfacetamida Sódica', 6, 'Inhiben la enzima dihidropteroato sintasa, bloquean la síntesis de ácido dihidrofólico y disminuye la síntesis de ácido fólico.', 7, '0.1', 1, 1, 'Viene con alcohol polivinilico 1.4%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (22, 'Trimetropin', 'Trimetropín', 6, 'Inhiben la enzima dihidropteroato sintasa, bloquean la síntesis de ácido dihidrofólico y disminuye la síntesis de ácido fólico.', 7, '0.003', 1, NULL, 'Acompañado de Polimixina B 0.01%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (23, 'Oflox', 'Ofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 7, '0.3%', 1, 1, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (24, 'Ciprodex', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 4, '0.3%', 7, NULL, 'Dexametasona 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (25, 'Ciproval', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 4, '0.3%', 8, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (26, 'Cilox', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 6, '0.3%', 8, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (27, 'Moxof', 'Moxifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 4, '0.005', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (28, 'Vigadexa', 'Moxifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 6, '0.005', 1, NULL, 'Dexametasona 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (29, 'ZYPRED', 'Gatifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 15, '0.3%', 7, NULL, 'Viene con prednisolona 1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (30, 'ZYMAXID', 'Gatifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 7, '0.005', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (31, 'Besivance', 'Besifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', NULL, '0.6%', NULL, NULL, 'No disponible en Colombia (por el momento)', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (32, 'Syvicrom', 'Cromoglicato sódico', 8, 'Inhibe la degranulación de los mastocitos impidiendo la liberación de mediadores inflamatorios como la histamina y leucotrienos.', 12, '0.04', 1, 4, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (33, 'Cromovital', 'Cromoglicato sódico', 8, 'Inhibe la degranulación de los mastocitos impidiendo la liberación de mediadores inflamatorios como la histamina y leucotrienos.', 10, '0.04', 1, 4, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (34, 'Oftacromax', 'Cromoglicato sódico', 8, 'Inhibe la degranulación de los mastocitos impidiendo la liberación de mediadores inflamatorios como la histamina y leucotrienos.', 11, '4%', 1, 4, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (35, 'NAABAK', 'Cromoglicato sódico', 8, 'Inhibe la degranulación de los mastocitos impidiendo la liberación de mediadores inflamatorios como la histamina y leucotrienos.', 9, '4.9%', 1, 5, 'No disponible en Colombia', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (36, 'Livostin', 'Levocabastina', 9, 'Es un antagonista selectivo del receptor H1 de la histamina, compite con la histamina por el receptor H1 de la célula efectora.', 30, '0.5%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (37, 'OQFRESH', 'Feniramina + Nafazolina', 9, 'Es un antagonista que se une para bloquear a los receptores H1, evitando la vasodilatación y el aumento de la permeabilidad vascular provocados por la reacción alérgica.', 1, '0.3%', 1, 5, 'Feniramina 0.3% - nafazolina 0.025%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (38, 'Alerxy-c', 'Olopatadina', 10, 'Combina el bloqueo de los receptores H1 de la histamina con la estabilización de membrana de los mastocitos.', 15, '0.005', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (39, 'Atergit', 'Epinastina', 10, 'Combina el bloqueo de los receptores H1 de la histamina con la estabilización de membrana de los mastocitos.', 5, '0.05%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (40, 'Oftic', 'Diclofenaco Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2)', 4, '0.001', 1, 3, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (41, '3A Ofteno', 'Diclofenaco Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2)', 8, '0.001', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (42, 'Voltaren Ophtha', 'Diclofenaco Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2)', 6, '0.001', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (43, 'Acular', 'Ketorolaco Trometamina', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-1)', 7, '0.5% / 0.4%', 1, NULL, 'Versión Less Salt 0.4% también disponible', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (44, 'Zebesten', 'Bromfenaco', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo', 8, '0.0009', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (45, 'Nepafenaco', 'Nepafenaco', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2)', 2, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (46, 'Nevanac', 'Nepafenaco', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2)', 6, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (47, 'Disalot', 'Loteprednol Etabonato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 11, '0.005', 7, 15, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (48, 'Lotemax', 'Loteprednol Etabonato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 28, '0.005', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (49, 'Flusure', 'Fluorometolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 11, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (50, 'Flumex', 'Fluorometolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 7, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (51, 'Ophthasona', 'Dexametasona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 11, '0.001', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (52, 'Maxidex', 'Dexametasona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 6, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (53, 'Pred-f', 'Prednisolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 7, '0.01', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (54, 'Durezol', 'Difluprednato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1, la cual bloquea la fosfolipasa A, reduciendo la liberación de ácido araquidónico.', 6, '0.0005', 4, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (55, 'Modusik A', 'Ciclosporina A', 13, 'Inhibe calcineurina, bloqueo activación y proliferación linfocitos T.', 8, '0.001', 1, 16, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (56, 'Restasis', 'Ciclosporina A', 13, 'Inhibe calcineurina, bloqueo activación y proliferación linfocitos T.', 7, '0.0005', 4, NULL, 'Emulsión (30 viales)', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (57, 'Ponti ofteno', 'Tetracaína', 14, 'Bloquea canales de sodio en las terminaciones nerviosas de la córnea y conjuntiva, impidiendo la transmisión del impulso doloroso y produciendo anestesia superficial.', 8, '0.5%', 1, 6, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (58, 'Alcaine', 'Proparacaína', 14, 'Estabiliza la membrana neuronal de las terminaciones nerviosas corneales y conjuntivales, bloqueando los canales de sodio y deteniendo la transmisión del dolor.', 6, '0.5%', 1, 6, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (59, 'OQ-Seina', 'Benoxinato (oxibuprocaína)', 14, 'Bloquea de manera reversible los canales de sodio dependientes de voltaje en las fibras nerviosas sensitivas de la córnea y conjuntiva.', 1, '0.4%', 1, 6, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (60, 'Cyclogil', 'Ciclopentolato', 15, 'Actúa competitivamente con la acetilcolina bloqueando por partes iguales los receptores muscarínicos M2 (iris) y M3 (músculo ciliar).', 6, '1%', 1, 7, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (61, 'Cicloftal', 'Ciclopentolato', 15, 'Actúa competitivamente con la acetilcolina bloqueando por partes iguales los receptores muscarínicos M2 (iris) y M3 (músculo ciliar).', 14, NULL, 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (62, 'Isopto Atropina', 'Atropina', 15, 'Actúa como un antagonista competitivo reversible con afinidad por los cinco subtipos de receptores muscarínicos de acetilcolina (MR1-MR5), actúa con mayor intensidad sobre los receptores M3 del músculo ciliar.', 6, '1%', 1, 8, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (63, 'Mydriacyl', 'Tropicamida', 15, 'Antagonista muscarínico con acción ciclopléjica y midriática. Bloquea los receptores muscarínicos del iris y del músculo ciliar.', 6, '1%', 1, 8, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (64, 'Fotorretin', 'Tropicamida + Fenilefrina', 15, 'Antagonista muscarínico con acción ciclopléjica y midriática. Bloquea los receptores muscarínicos del iris y del músculo ciliar.', 5, '0.5%', 1, NULL, 'Viene acompañado de fenilefrina 5%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (65, 'T-P Ofteno', 'Tropicamida + Fenilefrina', 15, 'Antagonista muscarínico con acción ciclopléjica y midriática. Bloquea los receptores muscarínicos del iris y del músculo ciliar.', 8, '0.8%', 1, NULL, 'Viene acompañado de fenilefrina 5%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (66, 'Hiprolub', 'Hidroxipropilmetilcelulosa', 16, 'Aumenta la viscosidad de la película lagrimal, prolonga su tiempo de permanencia y disminuye la evaporación. Forma una capa lubricante y protectora sobre el epitelio corneal y conjuntival.', 1, '0.3%', 1, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (67, 'Freegen', 'Carboximetilcelulosa', 16, 'Se adhiere a la superficie corneal y conjuntival, formando una capa lubricante que reduce la fricción palpebral, mejora la hidratación y disminuye la evaporación.', 1, '0.5%, 1%', 9, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (68, 'Optive', 'Carboximetilcelulosa', 16, 'Se adhiere a la superficie corneal y conjuntival, formando una capa lubricante que reduce la fricción palpebral, mejora la hidratación y disminuye la evaporación.', 6, '0.5%, 1%', 9, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (69, 'Genteal', 'Hipromelosa', 16, 'Se adhiere al epitelio corneal y conjuntival y a la mucina lagrimal, generando una película lubricante más estable y de mayor tiempo de permanencia que la HPMC.', 1, '0.3%', 9, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (70, 'Oftalub', 'Alcohol polivinílico', 17, 'Aumenta la viscosidad de la película lagrimal y forma una capa lubricante sobre córnea y conjuntiva. Reduce la fricción palpebral y mejora la estabilidad lagrimal.', 1, '1.4%', 1, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (71, 'TotalConfort', 'Polivinil-pirrolidona', 17, 'Se adhiere a la superficie ocular y retiene agua, estabilizando la película lagrimal y disminuyendo la evaporación.', 1, '0.5%', 1, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (72, 'Systane Ultra', 'Polietilenglicol', 17, 'Forma una capa hidratante sobre el epitelio y reduce la tensión superficial, mejorando la distribución de la lágrima y la estabilidad de la película lagrimal.', 6, '0.4%', 4, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (73, 'Acrylarm', 'Ácido poliacrílico', 17, 'Su alta viscosidad y mucoadhesividad permiten que forme un gel que se adhiere a mucina y epitelio corneal, prolongando el tiempo de contacto, reduciendo evaporación.', 1, '0.2%-2.5%', 2, 9, 'También: Refresh gel, siccafluid, xicrim', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (74, 'Kliner', 'Dextran 70', 18, 'Es un polisacárido ramificado, que aumenta la viscosidad de la película lagrimal y actúa como agente humectante. Forma una capa lubricante que reduce la fricción palpebral.', 1, '0.3%', 1, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (75, 'Toptear', 'Hialuronato de sodio', 18, 'Es un glicosaminoglicano con alta capacidad de retener agua y comportamiento viscoelástico. Se adhiere al epitelio corneal y a la mucina, formando una película hidratante y protectora.', 1, '0.1%, 0.4%', 1, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (76, 'Modusik A / Restasis', 'Ciclosporina', 19, 'Actúa como inmunomodulador tópico, inhibiendo la activación de linfocitos T mediante la inhibición de la calcineurina, reduciendo la producción de citocinas proinflamatorias en la superficie ocular.', 8, '0.1%', NULL, 17, 'También disponible como Closporil', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (77, 'Preparado magistral', 'Tacrolimus FK 506', 19, 'Inhibe la calcineurina de manera similar a la ciclosporina. Esta inhibición previene la activación de linfocitos T y la producción de citocinas proinflamatorias en la superficie ocular.', NULL, '0.1%, 0.03%', NULL, 17, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (78, 'Timolol TQ / Timoptic', 'Timolol maleato', 20, 'Bloquean receptores β1/β2 en cuerpo ciliar → ↓ producción de humor acuoso', 13, '0.5%', 5, 10, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (79, 'Xalatan®', 'Latanoprost', 21, 'Se unen a receptores FP → ↑ drenaje uveoscleral del humor acuoso', 6, '0.005%', 5, 11, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (80, 'Travatan Z®', 'Travoprost', 21, 'Se unen a receptores FP → ↑ drenaje uveoscleral del humor acuoso', 6, '0.004%', 5, 12, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (81, 'Lumigan®', 'Bimatoprost', 21, 'Se unen a receptores FP → ↑ drenaje uveoscleral del humor acuoso', 7, '0.03%', 5, 12, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (82, 'Zioptan®', 'Tafluprost', 21, 'Se unen a receptores FP → ↑ drenaje uveoscleral del humor acuoso', 30, '0.0015%', 5, 12, 'Gotas oftálmicas sin conservantes', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (83, 'Trusopt® / Dorzolamida genérica', 'Dorzolamida', 22, 'Inhiben anhidrasa carbónica tipo II → ↓ bicarbonato → ↓ producción de humor acuoso', 30, '0.02', 5, 13, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (84, 'Azopt®', 'Brinzolamida', 22, 'Inhiben anhidrasa carbónica tipo II → ↓ bicarbonato → ↓ producción de humor acuoso', 6, '0.01', 5, 13, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (85, 'Alphagan® / Combigan®', 'Brimonidina tartrato', 23, 'Estimulan receptores α2 → ↓ producción y ↑ drenaje de humor acuoso', 15, '0.15-0.2%', 5, 13, '*Combigan incluye timolol', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (86, 'Xalacom®', 'Latanoprost + Timolol', 24, 'Combina bloqueo β + ↑ drenaje uveoscleral para mayor efecto hipotensor', 6, '0.005/0.5%', 5, 12, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (87, 'Combigan®', 'Brimonidina + Timolol', 25, 'Combina agonista α2 + bloqueador β para sinergia hipotensora', 15, '0.2/0.5%', 5, 13, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (88, 'PRO-122*', 'Brom. + Timolol + Dorzolamida', 26, 'Tres mecanismos unidos para mayor eficiencia (ensayo clínico)', 8, '0.2/0.5/2%', 5, 18, 'Ensayo clínico', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (89, 'Simbrinza®', 'Brinzolamida + Brimonidina', 27, 'Combinación para mayor control de presión intraocular', 6, '1% / 0.2%', 5, 13, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (90, 'Oftaflox', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 27, '0.3%', 8, NULL, 'Viene con polimixina B y dexametasona', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (91, 'Conjuntin-S', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 7, '0.3%', 7, NULL, 'Viene con acetato de prednisolona y polimixina B', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (92, 'Maxitrol', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 20, '0.3%', 8, NULL, 'Viene con dexametasona y polimixina B', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (93, 'Gotabiotic', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 5, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (94, 'Gotabiotic-D', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 5, '0.3%', 1, NULL, 'Viene con dexametasona 0.005% y nafazolina 0.02%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (95, 'Gotabiotic-F', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 5, '0.3%', 9, 14, 'Viene con dexametasona 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (96, 'Ophthabracin', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 11, '0.3%', 1, 1, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (97, 'Ophthabracin-D', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 11, '0.3%', 1, NULL, 'Viene con dexametasona', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (98, 'Xolof', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 4, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (99, 'Tobraoftal', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 2, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (100, 'Tobraoftal-D', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 2, '0.3%', 7, NULL, 'Viene con 0.1% de dexametasona', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (101, 'Lotemicin', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 5, '0.3%', 7, NULL, 'Viene con loteprednol etabonato al 0.5%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (102, 'Tobragan D', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 7, '0.3%', 10, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (103, 'Tobracort', 'Tobramicina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 22, '0.3%', 7, NULL, 'Viene con dexametasona al 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (104, 'Terravital', 'Oxitetraciclina', 4, 'Se unen de forma irreversible a la unidad ribosomal 30s causando formación errónea de proteínas.', 24, '0.005', 2, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (105, 'Deltamid Ofteno', 'Sulfacetamida Sódica', 6, 'Inhiben la enzima dihidropteroato sintasa, bloquean la síntesis de ácido dihidrofólico.', 8, '0.1', 7, NULL, 'A. Prednisolona 0.5%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (106, 'Ocuflox', 'Ofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 7, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (107, 'Cifloblas', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 26, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (108, 'Wassercipro', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 3, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (109, 'Poenbiotic', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 5, '0.3%', 7, NULL, 'Dexametasona 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (110, 'Sophixin', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 8, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (111, 'Flobact', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 21, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (112, 'Flobact-D', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 21, '0.3%', 7, NULL, 'Viene con dexametasona al 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (113, 'Cixol', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 15, '0.3%', 7, NULL, 'Puede venir con Dexametasona 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (114, 'Cilodex', 'Ciprofloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 6, '0.3%', 9, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (115, 'Oftamox(d)', 'Moxifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 2, '0.005', 1, NULL, 'Viene con dexametasona al 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (116, 'Quimox', 'Moxifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 21, '0.005', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (117, 'gasyn', 'Gatifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 15, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (118, 'Poengatif', 'Gatifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 27, '0.3%', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (119, 'Gatidex', 'Gatifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 5, '0.3%', 7, NULL, 'Viene con dexametasona 0.1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (120, 'Carteof', 'Gatifloxacina', 7, 'Inhiben DNA girasa, impidiendo la replicación del ADN bacteriano.', 15, '0.3%', 7, NULL, 'Viene con acetato de prednisolona 1%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (121, 'Fazolin', 'Feniramina + Nafazolina', 9, 'Antagonista H1, evita vasodilatación y aumento de permeabilidad vascular.', 19, '0.3%', 1, 5, 'Feniramina 0.3% - nafazolina 0.016%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (122, 'Oftalirio', 'Antazolina + Nafazolina', 9, 'Antagonista H1, evita vasodilatación y aumento de permeabilidad vascular.', 30, '0.5%', 1, 5, 'Antazolina 0.5% - nafazolina 0.050%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (123, 'Optialerg', 'Antazolina + Nafazolina', 9, 'Antagonista H1, evita vasodilatación y aumento de permeabilidad vascular.', 18, '0.5%', 1, 5, 'Antazolina 0.5% - nafazolina 0.25%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (124, 'Vidizine', 'Antazolina + Nafazolina', 9, 'Antagonista H1, evita vasodilatación y aumento de permeabilidad vascular.', 17, '0.05%', 1, 5, 'Antazolina 0.05% - nafazolina 0.04%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (125, 'Relestat', 'Epinastina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 7, '0.05%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (126, 'Kenaler', 'Ketotifeno', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 11, '0.05%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (127, 'Ketoftal', 'Ketotifeno', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 3, '0.025%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (128, 'Oftaler', 'Ketotifeno', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 4, '0.025%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (129, 'Zaditen', 'Ketotifeno', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 6, '0.025%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (130, 'Olopat', 'Olopatadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 5, '0.2%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (131, 'Patanol', 'Olopatadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 6, '0.2%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (132, 'Oloftal', 'Olopatadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 3, '0.2%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (133, 'Olodina', 'Olopatadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 11, '0.2%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (134, 'Alap', 'Olopatadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 22, '0.2%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (135, 'Dolcettina', 'Alcaftadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 30, '1.5%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (136, 'Traler', 'Alcaftadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 5, '1.5%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (137, 'Alecri', 'Alcaftadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 30, '0.25%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (138, 'Lastacaft', 'Alcaftadina', 10, 'Combina bloqueo H1 con estabilización de membrana de mastocitos.', 7, '0.25%', 1, 5, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (139, 'Wasservolt', 'Diclofenaco Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2).', 29, '0.001', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (140, 'Dinaclord', 'Diclofenaco Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2).', 1, '0.001', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (141, 'Dicloabak', 'Diclofenaco Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2).', 9, '0.001', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (142, 'Poenkerat', 'Ketorolaco Trometamina', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-1).', 5, '0.005', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (143, 'Ophthaker', 'Ketorolaco Trometamina', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-1).', 11, '0.005', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (144, 'Kenalgesic', 'Ketorolaco Trometamina', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-1).', 1, '0.005', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (145, 'Bronax', 'Bromfenaco', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo.', 5, '0.0009', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (146, 'Natax', 'Bromfenaco', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo.', 5, '0.0009', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (147, 'Ocufen', 'Flurbiprofeno Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo.', 7, '0.0003', 1, NULL, 'No disponible en Colombia', FALSE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (148, 'Neolag One', 'Nepafenaco', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo (mayor potencia COX-2).', 15, '0.003', 7, NULL, 'No disponible en Colombia', FALSE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (149, 'Opticam', 'Meloxicam', 11, 'No completamente pero selectivo de COX-2.', 11, '0.0003', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (150, 'Coxylan', 'Meloxicam', 11, 'No completamente pero selectivo de COX-2.', 8, '0.0003', 1, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (151, 'Talof', 'Loteprednol Etabonato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 5, '0.002', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (152, 'Lotesoft', 'Loteprednol Etabonato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 5, '0.005', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (153, 'Oftaprednol Max', 'Loteprednol Etabonato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 2, '0.005', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (154, 'LOTEMICIN', 'Loteprednol Etabonato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 5, '0.005', 7, NULL, 'Viene con tobramicina 0.3%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (155, 'Flumetol NF', 'Fluorometolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 8, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (156, 'Aflarex', 'Fluorometolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 6, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (157, 'Fluoftal', 'Fluorometolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 26, '0.001', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (158, 'Prefox-T', 'Prednisolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 11, '0.01', 7, NULL, 'Viene con Fenilefrina 0.12%', TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (159, 'Cortioftal', 'Prednisolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 2, '0.01', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (160, 'Proxten Plus', 'Prednisolona', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 11, '0.01', 7, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (161, 'Tolf', 'Difluprednato', 12, 'Inhibición de síntesis de mediadores proinflamatorios, induciendo lipocortina-1.', 5, '0.0005', 4, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (162, 'Glaucoprost', 'Travoprost', 21, 'Se unen a receptores FP → ↑ drenaje uveoscleral del humor acuoso.', 6, '0.004%', 5, 12, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (163, 'Ocufen', 'Flurbiprofeno Sódico', 11, 'Inhibición de la síntesis de prostaglandinas, No selectivo.', 7, '0.0003', 1, NULL, 'No disponible en Colombia', FALSE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (164, 'ciclopentolato', 'Ciclopentolato', 15, 'Actúa competitivamente con la acetilcolina bloqueando los receptores muscarínicos M2 (iris) y M3 (músculo ciliar).', 5, NULL, NULL, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (165, 'ciclopentolato', 'Ciclopentolato', 15, 'Actúa competitivamente con la acetilcolina bloqueando los receptores muscarínicos M2 (iris) y M3 (músculo ciliar).', 1, NULL, NULL, NULL, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (166, 'Trehalosa', 'Trehalosa', 18, 'Disacárido que actúa como osmoprotector y estabilizador de membranas celulares.', NULL, NULL, 1, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (167, 'Humylub / Splash Tears', 'Condroitín sulfato', 18, 'Glicosaminoglicano sulfatado. Retiene agua, aumenta viscosidad.', NULL, '0.18%, 0.1%', NULL, 9, NULL, TRUE);
INSERT INTO product_details (id_product, commercial_name, generic_name, id_family, action_mechanism, id_laboratory, concentration, id_pharmaceutical_form, id_posology, notes, is_active) VALUES (168, 'Galactomanano (Hp-Guar)', 'Galactomanano hidroxipropilado', 18, 'Forma matriz gelificada en superficie ocular.', NULL, NULL, NULL, 9, NULL, TRUE);